### PR TITLE
Support comments in the redirects file

### PR DESCRIPTION
**Pull request by phlax**
this allows devs to explain why something has been added, or remove after a certain amount of time

### CODE REVIEW

**Comment by Daltz333** [comment]
Can you add a test that reads a file with comments and verifies redirects are still added?

**Comment by phlax** [comment]
sure

**Comment by phlax** [comment]
ci seems to be failing for unrelated reasons tho i think

**Comment by phlax** [comment]
@Daltz333 iiuc just adding this sample in `tests/root/ext` should test - can you confirm ? I dont think i can see CI as its falling over

**Comment by TheTripleV** [comment]
CI is operational again. Could you rebase off of master to get the fix?

**Review by TheTripleV — CHANGES_REQUESTED** [review]
Since this pr changes functionality in the `create_graph` function, tests should go in `tests/test_create_graph.py`.

I'd say the only test required is:
rediraffe.txt has a line with a comment and that line should not appear in the output of `create_graph`.

**Comment by phlax** [comment]
@TheTripleV i think ive moved the test to the right place, lmk if there are any further changes required to land

**Review by TheTripleV — APPROVED** [review]
LGTM!

**Review by Daltz333 — APPROVED** [review]

**Pull request merged**
